
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;
import jxl.Workbook;
import jxl.WorkbookSettings;
import jxl.write.Label;
import jxl.write.WritableSheet;
import jxl.write.WritableWorkbook;
import jxl.write.WriteException;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import proclass.BinaryImage;
import proclass.CSVreader;
import proclass.Checkscore;
import proclass.LineDetect;
import proclass.Vertical;
import proclass.horizontal;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on 15 ธ.ค. 2554, 15:15:41
 */
/**
 *
 * @author 0X2531
 */


public class NewJFrame extends javax.swing.JFrame {

    
    private DefaultTableModel tt;
    String id[]=new String [50];
    String name[]=new String [50];
    String lastname[]=new String [50];
    String idsubject[]=new String [50];
    String namesubject[]=new String [50];
    int check=0;
    int score[]=new int[50];
    int avscore[]=new int[6];
    int ck[]=new int[50];
    int inc=0;
    public static int pgb=0; 
    BufferedImage image1=null;
		BufferedImage image11=null;
		BufferedImage image2=null;
		BufferedImage image21=null;
		BufferedImage image3[]= new BufferedImage[20];
		BufferedImage image4[]= new BufferedImage[15];
		BufferedImage studentid=null;
		BufferedImage subjectid=null;
		BufferedImage cstudentid[]= new BufferedImage[12];
		BufferedImage chkstudentid[][]= new BufferedImage[14][10];
		BufferedImage chksubjectid[][]= new BufferedImage[9][10];
		BufferedImage cstudentid2[]= new BufferedImage[20];
		BufferedImage csubjectid2[]= new BufferedImage[20];
		BufferedImage csubjectid[]= new BufferedImage[12];
		BufferedImage cchoid1[]= new BufferedImage[32];
		BufferedImage cchoid2[]= new BufferedImage[32];
		BufferedImage cchoid3[]= new BufferedImage[32];
		BufferedImage cchoid4[]= new BufferedImage[32];
		BufferedImage cchoid5[]= new BufferedImage[130];
		BufferedImage cutchoid[]= new BufferedImage[5];
		BufferedImage fullchoid[][]= new BufferedImage[120][5];
		BufferedImage afullchoid[][]= new BufferedImage[120][5];
		BufferedImage choid1=null;
		BufferedImage choid2=null;
		BufferedImage choid3=null;
		BufferedImage choid4=null;
		horizontal hr= new horizontal();
		Vertical vr= new Vertical(); 
		BinaryImage BI = new BinaryImage();
		Checkscore SC = new Checkscore();
		CSVreader cs =new CSVreader(); 
                String[] buffstudentid=new String[50];
                String[] buffsubjectid=new String[50];
                int abuffchoid[][] = new int[120][5];
                int chartscore[][] = new int[50][5];
                int buffchoidexam[][][] = new int[50][120][5];
                int ce=0;
    
    public NewJFrame() {
        initComponents();
    }
    
    
public static class thread1 implements Runnable{
    public void run(){
    for(int i=0;i<100;i++){
    //System.out.println(pgb);
    jProgressBar1.setValue(i);
    jProgressBar1.repaint(); 
                try {
                    Thread.sleep(100);
                } catch (InterruptedException ex) {
                    Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
    }
}
} 

static public boolean deleteDirectory(File path) {
    if( path.exists() ) {
      File[] files = path.listFiles();
      for(int i=0; i<files.length; i++) {
         if(files[i].isDirectory()) {
           deleteDirectory(files[i]);
         }
         else {
           files[i].delete();
         }
      }
    }
    return( path.delete() );
  }
//public static class thread2 implements Runnable{
  //  public void run(){
    //    pgb=pgb+10;
      //      try {
        //        Thread.sleep(1000);
        //    } catch (InterruptedException ex) {
        //        Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        //    }
//}
//} 
     /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        process = new javax.swing.JPanel();
        checker = new javax.swing.JButton();
        file = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        adstudent = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        status = new javax.swing.JLabel();
        addsubject = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        subject = new javax.swing.JLabel();
        checkexam = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        answer = new javax.swing.JLabel();
        exam = new javax.swing.JLabel();
        proc = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jProgressBar1 = new javax.swing.JProgressBar();
        chart1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        ch1 = new javax.swing.JLabel();
        ch2 = new javax.swing.JLabel();
        ch3 = new javax.swing.JLabel();
        ch4 = new javax.swing.JLabel();
        ch5 = new javax.swing.JLabel();
        ch6 = new javax.swing.JLabel();
        ch7 = new javax.swing.JLabel();
        chart2 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        sc1 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        sc2 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        sc3 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        sc4 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        sc5 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Examination Checker");
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(NewJFrame.class);
        setBackground(resourceMap.getColor("background")); // NOI18N
        setResizable(false);

        process.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ประมวลผลภาพ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("CordiaUPC", 0, 18))); // NOI18N
        process.setName("process"); // NOI18N

        checker.setFont(new java.awt.Font("CordiaUPC", 0, 18)); // NOI18N
        checker.setText("ตรวจข้อสอบ");
        checker.setEnabled(false);
        checker.setName("checker"); // NOI18N
        checker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout processLayout = new javax.swing.GroupLayout(process);
        process.setLayout(processLayout);
        processLayout.setHorizontalGroup(
            processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(processLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(checker, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addContainerGap())
        );
        processLayout.setVerticalGroup(
            processLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(processLayout.createSequentialGroup()
                .addComponent(checker, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        file.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "เพิ่มข้อมูล", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("CordiaUPC", 0, 18))); // NOI18N
        file.setName("file"); // NOI18N

        jButton1.setFont(new java.awt.Font("CordiaUPC", 0, 18)); // NOI18N
        jButton1.setText("เลือกไฟล์รายชื่อ");
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jButton2.setText("เลือกไฟล์รายวิชา");
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fileLayout = new javax.swing.GroupLayout(file);
        file.setLayout(fileLayout);
        fileLayout.setHorizontalGroup(
            fileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fileLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addContainerGap())
        );
        fileLayout.setVerticalGroup(
            fileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fileLayout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.CardLayout());

        adstudent.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        adstudent.setName("adstudent"); // NOI18N
        adstudent.setPreferredSize(new java.awt.Dimension(620, 578));

        jLabel1.setFont(new java.awt.Font("CordiaUPC", 1, 24));
        jLabel1.setText("การเพิ่มข้อมูลนักศึกษา");
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setFont(new java.awt.Font("CordiaUPC", 1, 18));
        jLabel2.setText("การเพิ่มข้อมูลรายชื่อเข้าในโปนแกรมต้องเป็นไฟล์นามสกุล .CSV เท่านั้น");
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setFont(new java.awt.Font("CordiaUPC", 1, 18));
        jLabel3.setText("ตัวอย่างการเตรียมไฟล์");
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel4.setText("1.) เปิดโปรแกรม Microsoft Office Excel ");
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel5.setText("2.) เพิ่มข้อมูลรหัสนักศึกษา และ ชื่อ-นามสกุล   ");
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/picexcel.jpg"))); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        jLabel6.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel6.setText("3.) ทำการบันทึกไฟล์เป็นนามสกุล .CSV เท่านั้น");
        jLabel6.setName("jLabel6"); // NOI18N

        jButton4.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jButton4.setText("เพิ่มรายชื่อนักศึกษา");
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "รหัสนักศึกษา", "ชื่อ", "นามสกุล"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setResizable(false);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(150);
        jTable1.getColumnModel().getColumn(1).setResizable(false);
        jTable1.getColumnModel().getColumn(2).setResizable(false);

        jLabel15.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel15.setName("jLabel15"); // NOI18N

        status.setFont(new java.awt.Font("CordiaUPC", 1, 18));
        status.setForeground(new java.awt.Color(204, 0, 0));
        status.setText("ชื่อไฟล์ :");
        status.setName("status"); // NOI18N

        javax.swing.GroupLayout adstudentLayout = new javax.swing.GroupLayout(adstudent);
        adstudent.setLayout(adstudentLayout);
        adstudentLayout.setHorizontalGroup(
            adstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adstudentLayout.createSequentialGroup()
                .addGroup(adstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adstudentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(adstudentLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2))
                    .addGroup(adstudentLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel3))
                    .addGroup(adstudentLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(adstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addGroup(adstudentLayout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addGroup(adstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(status)
                                    .addComponent(jLabel15)))))
                    .addGroup(adstudentLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        adstudentLayout.setVerticalGroup(
            adstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adstudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(adstudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(status))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(adstudent, "card3");

        addsubject.setName("addsubject"); // NOI18N

        jLabel8.setFont(new java.awt.Font("CordiaUPC", 1, 24));
        jLabel8.setText("การเพิ่มข้อมูลรายวิชา");
        jLabel8.setName("jLabel8"); // NOI18N

        jLabel9.setFont(new java.awt.Font("CordiaUPC", 1, 18));
        jLabel9.setText("การเพิ่มข้อมูลรายชื่อเข้าในโปนแกรมต้องเป็นไฟล์นามสกุล .CSV เท่านั้น");
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setFont(new java.awt.Font("CordiaUPC", 1, 18));
        jLabel10.setText("ตัวอย่างการเตรียมไฟล์");
        jLabel10.setName("jLabel10"); // NOI18N

        jLabel11.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel11.setText("1.) เปิดโปรแกรม Microsoft Office Excel ");
        jLabel11.setName("jLabel11"); // NOI18N

        jLabel12.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel12.setText("2.) เพิ่มข้อมูลรหัสวิชา และ ชื่อวิชา   ");
        jLabel12.setName("jLabel12"); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/picexcel2.jpg"))); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        jLabel14.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel14.setText("3.) ทำการบันทึกไฟล์เป็นนามสกุล .CSV เท่านั้น");
        jLabel14.setName("jLabel14"); // NOI18N

        jButton5.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jButton5.setText("เพิ่มรายวิชา");
        jButton5.setName("jButton5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTable2.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "รหัสวิชา", "ชื่อรายวิชา"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setGridColor(new java.awt.Color(0, 0, 0));
        jTable2.setName("jTable2"); // NOI18N
        jScrollPane2.setViewportView(jTable2);
        jTable2.getColumnModel().getColumn(0).setResizable(false);
        jTable2.getColumnModel().getColumn(0).setPreferredWidth(150);
        jTable2.getColumnModel().getColumn(1).setResizable(false);

        subject.setFont(new java.awt.Font("CordiaUPC", 1, 18));
        subject.setForeground(new java.awt.Color(204, 0, 0));
        subject.setText("ชื่อไฟล์ :");
        subject.setName("subject"); // NOI18N

        javax.swing.GroupLayout addsubjectLayout = new javax.swing.GroupLayout(addsubject);
        addsubject.setLayout(addsubjectLayout);
        addsubjectLayout.setHorizontalGroup(
            addsubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addsubjectLayout.createSequentialGroup()
                .addGroup(addsubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addsubjectLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8))
                    .addGroup(addsubjectLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel9))
                    .addGroup(addsubjectLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(addsubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addGroup(addsubjectLayout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(subject))))
                    .addGroup(addsubjectLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel10)))
                .addContainerGap(119, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addsubjectLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        addsubjectLayout.setVerticalGroup(
            addsubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addsubjectLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(addsubjectLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subject))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel2.add(addsubject, "card2");

        checkexam.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        checkexam.setName("checkexam"); // NOI18N
        checkexam.setPreferredSize(new java.awt.Dimension(620, 578));

        jLabel16.setFont(new java.awt.Font("CordiaUPC", 1, 24));
        jLabel16.setText("การประมวลผลภาพ");
        jLabel16.setName("jLabel16"); // NOI18N

        jButton3.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jButton3.setText("เลือกไฟล์กระดาษคำตอบ");
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("CordiaUPC", 0, 18)); // NOI18N
        jButton6.setText("เลือกไฟล์คำตอบ");
        jButton6.setName("jButton6"); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        answer.setFont(new java.awt.Font("CordiaUPC", 1, 18));
        answer.setForeground(new java.awt.Color(204, 0, 0));
        answer.setText("ชื่อไฟล์ : ");
        answer.setName("answer"); // NOI18N

        exam.setFont(new java.awt.Font("CordiaUPC", 1, 18));
        exam.setForeground(new java.awt.Color(204, 0, 0));
        exam.setText("ชื่อโฟลเดอร์ : ");
        exam.setName("exam"); // NOI18N

        proc.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        proc.setText("ตรวจข้อสอบ");
        proc.setEnabled(false);
        proc.setName("proc"); // NOI18N
        proc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procActionPerformed(evt);
            }
        });

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jTable3.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "รหัสนักศึกษา", "ชื่อนักศึกษา", "รหัสวิชา", "ชื่อวิชา", "คะแนน"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setName("jTable3"); // NOI18N
        jScrollPane3.setViewportView(jTable3);
        jTable3.getColumnModel().getColumn(0).setResizable(false);
        jTable3.getColumnModel().getColumn(0).setPreferredWidth(150);
        jTable3.getColumnModel().getColumn(1).setResizable(false);
        jTable3.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTable3.getColumnModel().getColumn(2).setResizable(false);
        jTable3.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTable3.getColumnModel().getColumn(3).setResizable(false);
        jTable3.getColumnModel().getColumn(3).setPreferredWidth(200);
        jTable3.getColumnModel().getColumn(4).setResizable(false);
        jTable3.getColumnModel().getColumn(4).setPreferredWidth(100);

        jProgressBar1.setName("jProgressBar1"); // NOI18N

        javax.swing.GroupLayout checkexamLayout = new javax.swing.GroupLayout(checkexam);
        checkexam.setLayout(checkexamLayout);
        checkexamLayout.setHorizontalGroup(
            checkexamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkexamLayout.createSequentialGroup()
                .addGroup(checkexamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkexamLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel16))
                    .addGroup(checkexamLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(checkexamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(proc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(checkexamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exam)
                            .addComponent(answer)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(checkexamLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 590, Short.MAX_VALUE)))
                .addContainerGap())
        );
        checkexamLayout.setVerticalGroup(
            checkexamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(checkexamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(checkexamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(answer))
                .addGap(18, 18, 18)
                .addGroup(checkexamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(exam))
                .addGroup(checkexamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(checkexamLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(proc))
                    .addGroup(checkexamLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel2.add(checkexam, "card3");

        chart1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chart1.setName("chart1"); // NOI18N
        chart1.setPreferredSize(new java.awt.Dimension(620, 578));

        jLabel17.setName("jLabel17"); // NOI18N

        jLabel18.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel18.setText("จำนวนนักศึกษาทั้งหมด");
        jLabel18.setName("jLabel18"); // NOI18N

        jLabel19.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel19.setText("ระดับคะแนน      0 - 20 :");
        jLabel19.setName("jLabel19"); // NOI18N

        jLabel20.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel20.setText("ระดับคะแนน    20 - 40 :");
        jLabel20.setName("jLabel20"); // NOI18N

        jLabel21.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel21.setText("ระดับคะแนน    40 - 60 :");
        jLabel21.setName("jLabel21"); // NOI18N

        jLabel22.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel22.setText("ระดับคะแนน    60 - 80 :");
        jLabel22.setName("jLabel22"); // NOI18N

        jLabel23.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel23.setText("ระดับคะแนน   80 - 100 :");
        jLabel23.setName("jLabel23"); // NOI18N

        jLabel24.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel24.setText("ระดับคะแนน 100 - 120 :");
        jLabel24.setName("jLabel24"); // NOI18N

        jLabel25.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel25.setText("คน");
        jLabel25.setName("jLabel25"); // NOI18N

        jLabel26.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel26.setText("คน");
        jLabel26.setName("jLabel26"); // NOI18N

        jLabel27.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel27.setText("คน");
        jLabel27.setName("jLabel27"); // NOI18N

        jLabel28.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel28.setText("คน");
        jLabel28.setName("jLabel28"); // NOI18N

        jLabel29.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel29.setText("คน");
        jLabel29.setName("jLabel29"); // NOI18N

        jLabel30.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel30.setText("คน");
        jLabel30.setName("jLabel30"); // NOI18N

        jLabel31.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel31.setText("คน");
        jLabel31.setName("jLabel31"); // NOI18N

        ch1.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        ch1.setText("10");
        ch1.setName("ch1"); // NOI18N

        ch2.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        ch2.setText("10");
        ch2.setName("ch2"); // NOI18N

        ch3.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        ch3.setText("10");
        ch3.setName("ch3"); // NOI18N

        ch4.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        ch4.setText("10");
        ch4.setName("ch4"); // NOI18N

        ch5.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        ch5.setText("10");
        ch5.setName("ch5"); // NOI18N

        ch6.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        ch6.setText("10");
        ch6.setName("ch6"); // NOI18N

        ch7.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        ch7.setText("10");
        ch7.setName("ch7"); // NOI18N

        javax.swing.GroupLayout chart1Layout = new javax.swing.GroupLayout(chart1);
        chart1.setLayout(chart1Layout);
        chart1Layout.setHorizontalGroup(
            chart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chart1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(chart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(chart1Layout.createSequentialGroup()
                        .addGroup(chart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21))
                        .addGap(9, 9, 9)
                        .addGroup(chart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ch1)
                            .addComponent(ch2)
                            .addComponent(ch3)
                            .addComponent(ch4))
                        .addGap(18, 18, 18)
                        .addGroup(chart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addGroup(chart1Layout.createSequentialGroup()
                                .addGroup(chart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel26))
                                .addGap(29, 29, 29)
                                .addGroup(chart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel24))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(chart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ch5)
                                    .addComponent(ch6)
                                    .addComponent(ch7))
                                .addGap(18, 18, 18)
                                .addGroup(chart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel31)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel29))))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        chart1Layout.setVerticalGroup(
            chart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chart1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(chart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(chart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(chart1Layout.createSequentialGroup()
                            .addGroup(chart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(ch1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(chart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(chart1Layout.createSequentialGroup()
                                    .addGroup(chart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel19)
                                        .addComponent(ch2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(chart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel20)
                                        .addComponent(ch3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(chart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel21)
                                        .addComponent(ch4)))
                                .addGroup(chart1Layout.createSequentialGroup()
                                    .addGroup(chart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel22)
                                        .addComponent(ch5))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(chart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel23)
                                        .addComponent(ch6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(chart1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel24)
                                        .addComponent(ch7)))))
                        .addGroup(chart1Layout.createSequentialGroup()
                            .addComponent(jLabel25)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel26)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel27)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel28)))
                    .addGroup(chart1Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel31)))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        jPanel2.add(chart1, "card3");

        chart2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        chart2.setName("chart2"); // NOI18N
        chart2.setPreferredSize(new java.awt.Dimension(620, 578));

        jLabel32.setName("jLabel32"); // NOI18N

        jLabel33.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel33.setText("รหัสนักศึกษา");
        jLabel33.setName("jLabel33"); // NOI18N

        jComboBox1.setName("jComboBox1"); // NOI18N
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel34.setText("jLabel34");
        jLabel34.setName("jLabel34"); // NOI18N

        jLabel35.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel35.setText("จำนวนข้อทั้งหมด");
        jLabel35.setName("jLabel35"); // NOI18N

        jLabel36.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel36.setText("ข้อ ก. จำนวน");
        jLabel36.setName("jLabel36"); // NOI18N

        jLabel37.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel37.setText("ข้อ ข. จำนวน");
        jLabel37.setName("jLabel37"); // NOI18N

        jLabel38.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel38.setText("ข้อ ค. จำนวน");
        jLabel38.setName("jLabel38"); // NOI18N

        jLabel39.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel39.setText("ข้อ ง. จำนวน");
        jLabel39.setName("jLabel39"); // NOI18N

        jLabel40.setFont(new java.awt.Font("CordiaUPC", 0, 18));
        jLabel40.setText("ข้อ จ. จำนวน");
        jLabel40.setName("jLabel40"); // NOI18N

        total.setText("120");
        total.setName("total"); // NOI18N

        jLabel42.setText("ข้อ");
        jLabel42.setName("jLabel42"); // NOI18N

        sc1.setText("10");
        sc1.setName("sc1"); // NOI18N

        jLabel44.setText("ข้อ");
        jLabel44.setName("jLabel44"); // NOI18N

        sc2.setText("10");
        sc2.setName("sc2"); // NOI18N

        jLabel46.setText("ข้อ");
        jLabel46.setName("jLabel46"); // NOI18N

        sc3.setText("10");
        sc3.setName("sc3"); // NOI18N

        jLabel48.setText("ข้อ");
        jLabel48.setName("jLabel48"); // NOI18N

        sc4.setText("10");
        sc4.setName("sc4"); // NOI18N

        jLabel50.setText("ข้อ");
        jLabel50.setName("jLabel50"); // NOI18N

        sc5.setText("0");
        sc5.setName("sc5"); // NOI18N

        jLabel52.setText("ข้อ");
        jLabel52.setName("jLabel52"); // NOI18N

        javax.swing.GroupLayout chart2Layout = new javax.swing.GroupLayout(chart2);
        chart2.setLayout(chart2Layout);
        chart2Layout.setHorizontalGroup(
            chart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chart2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(chart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chart2Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(18, 18, 18)
                        .addComponent(total)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel42))
                    .addGroup(chart2Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addGap(18, 18, 18)
                        .addComponent(sc3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel48))
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(chart2Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel34))
                    .addGroup(chart2Layout.createSequentialGroup()
                        .addGroup(chart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addComponent(jLabel36))
                        .addGap(18, 18, 18)
                        .addGroup(chart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(chart2Layout.createSequentialGroup()
                                .addComponent(sc1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel44))
                            .addGroup(chart2Layout.createSequentialGroup()
                                .addComponent(sc2)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel46)))
                        .addGap(80, 80, 80)
                        .addGroup(chart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(chart2Layout.createSequentialGroup()
                                .addComponent(jLabel40)
                                .addGap(18, 18, 18)
                                .addComponent(sc5)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel52))
                            .addGroup(chart2Layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addGap(18, 18, 18)
                                .addComponent(sc4)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel50)))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        chart2Layout.setVerticalGroup(
            chart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chart2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(chart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(chart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(total)
                    .addComponent(jLabel42))
                .addGap(11, 11, 11)
                .addGroup(chart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(chart2Layout.createSequentialGroup()
                        .addGroup(chart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(sc1)
                            .addComponent(jLabel44))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(chart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(sc2)
                            .addComponent(jLabel46))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(chart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel38)
                            .addComponent(sc3)
                            .addComponent(jLabel48)))
                    .addGroup(chart2Layout.createSequentialGroup()
                        .addGroup(chart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39)
                            .addComponent(jLabel50)
                            .addComponent(sc4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(chart2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel40)
                            .addComponent(sc5)
                            .addComponent(jLabel52))))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jPanel2.add(chart2, "card3");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "แสดงรายงาน", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("CordiaUPC", 0, 18))); // NOI18N
        jPanel1.setName("jPanel1"); // NOI18N

        jButton7.setText("PDF File");
        jButton7.setEnabled(false);
        jButton7.setName("jButton7"); // NOI18N
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("แสดงกราฟคะแนน");
        jButton8.setEnabled(false);
        jButton8.setName("jButton8"); // NOI18N
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("กราฟแสดงข้อกา");
        jButton9.setEnabled(false);
        jButton9.setName("jButton9"); // NOI18N
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(process, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(file, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(file, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(process, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 608, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
adstudent.setVisible(false);
addsubject.setVisible(true);
checkexam.setVisible(false);
chart1.setVisible(false);
chart2.setVisible(false);
}//GEN-LAST:event_jButton2ActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
adstudent.setVisible(true);
addsubject.setVisible(false);
checkexam.setVisible(false);
chart1.setVisible(false);
chart2.setVisible(false);
}//GEN-LAST:event_jButton1ActionPerformed

private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            File filename = new File("");
            JFileChooser ch = new JFileChooser();
            ch.setFileSelectionMode(0);
            int sts = ch.showOpenDialog(null);
            filename=ch.getSelectedFile();
            status.setText("ชื่อไฟล์ : "+filename.getName());
            CSVreader cs = new CSVreader();
            
            for(int i=0;i<50;i++){
            id[i]="";
            name[i]="";
            lastname[i]="";
            }
            int cl=cs.readcsvstudent(filename.getPath(), id, name, lastname);
            for(int i=0;i<50;i++){
            jTable1.setValueAt(id[i], i, 0);
            jTable1.setValueAt(name[i], i, 1);
            jTable1.setValueAt(lastname[i], i, 2);
            }
            if(check>0){
                checker.setEnabled(true);
            }
            check=check+1;
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_jButton4ActionPerformed

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
try {
            File filename = new File("");
            JFileChooser ch = new JFileChooser();
            ch.setFileSelectionMode(0);
            int sts = ch.showOpenDialog(null);
            filename=ch.getSelectedFile();
            subject.setText("ชื่อไฟล์ : "+filename.getName());
            CSVreader cs = new CSVreader();  
            for(int i=0;i<50;i++){
            idsubject[i]="";
            namesubject[i]="";
            }
            int cl=cs.readcsvsubject(filename.getPath(), idsubject, namesubject);
            for(int i=0;i<50;i++){
            jTable2.setValueAt(idsubject[i], i, 0);
            jTable2.setValueAt(namesubject[i], i, 1);
            }
            if(check>0){
                checker.setEnabled(true);
            }
            check=check+1;
        } catch (FileNotFoundException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_jButton5ActionPerformed

private void checkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkerActionPerformed
checkexam.setVisible(true);
adstudent.setVisible(false);
addsubject.setVisible(false);
chart1.setVisible(false);
chart2.setVisible(false);

}//GEN-LAST:event_checkerActionPerformed

private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            File filename = new File("");
            JFileChooser ch = new JFileChooser();
            ch.setFileSelectionMode(0);
            int sts = ch.showOpenDialog(null);
            filename=ch.getSelectedFile();
            answer.setText("ชื่อไฟล์ : "+filename.getName());
            try {
			File file = new File(filename.getPath());
            image11 = ImageIO.read(file);
		} catch (IOException e) {
			System.err.println("Cannot open the file.");
		}
            int rgb11[][] = new int[image11.getWidth()][image11.getHeight()];
            BI.CBinaryImage(image11,rgb11);
	    image21 = new BufferedImage(image11.getWidth(),image11.getHeight(),BufferedImage.TYPE_INT_RGB);	
		BI.getrgb(image11, image21, rgb11);
		hr.Cuthorizontal(image11,image21,image3,rgb11);
		vr.CutVertical(image3,image4,1);
		studentid=image4[0];
		subjectid=image4[1];
		vr.CutVertical(image3,image4,2);
		choid1=image4[0];
		choid2=image4[1];
		choid3=image4[2];
		choid4=image4[3];
                int cc = 0;
		hr.CutExamHor(choid1,cchoid1);
		for(int i=1;i<31;i++){
			cchoid5[cc]=cchoid1[i];
			cc=cc+1;
		}
		hr.CutExamHor(choid2,cchoid2);
		for(int i=1;i<31;i++){
			cchoid5[cc]=cchoid2[i];
			cc=cc+1;
		}
		hr.CutExamHor(choid3,cchoid3);
		for(int i=1;i<31;i++){
			cchoid5[cc]=cchoid3[i];
			cc=cc+1;
		}
		hr.CutExamHor(choid4,cchoid4);
		for(int i=1;i<31;i++){
			cchoid5[cc]=cchoid4[i];
			cc=cc+1;
		}
		
		for(int x=0;x<120;x++){
			vr.CutExamVer(cchoid5, cutchoid, x);
				for(int i=0;i<5;i++){
					afullchoid[x][i]=cutchoid[i];
				}
			}
  	
		SC.checkchoid(afullchoid,abuffchoid);

	
}//GEN-LAST:event_jButton3ActionPerformed

private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
           //thread1 th = new thread1(); 
            LineDetect l1 = new LineDetect();
            File fd = new File("D:\\dataexam\\tmp");
            boolean chk = fd.isDirectory();
                if(chk){
                    deleteDirectory(fd);
                }
               
    
            File filename = new File("");
            JFileChooser ch = new JFileChooser();
            ch.setFileSelectionMode(1);
            int sts = ch.showOpenDialog(null);
            filename=ch.getSelectedFile();
            exam.setText("ชื่อโฟลเดอร์ : "+filename.getName());
            File[] listOfFiles = filename.listFiles();
            ce=0;
            inc=100/filename.listFiles().length;
            for(int c=0;c<filename.listFiles().length;c++){ 
                
                //pgb=pgb+inc;
                //th.run();          
                try {
			File file = new File(listOfFiles[c].getPath());
			image1 = ImageIO.read(file);
                                                 
                    } catch (IOException e) {
			System.err.println("Cannot open the file.");
                    }
                int rgb[][] = new int[image1.getWidth()][image1.getHeight()];
		int buffchoid[][] = new int[120][5];
		String Stdid,sjid;
		BI.CBinaryImage(image1,rgb);
		image2 = new BufferedImage(image1.getWidth(),image1.getHeight(),BufferedImage.TYPE_INT_RGB);
                BI.getrgb(image1, image2, rgb);
                
                int chkahngle= l1.checkline(image2.getSubimage(image2.getWidth()/2, image2.getHeight()/2, 100, 200));
		
                System.out.println(chkahngle);
                //BI.tmpwriteImage(image2.getSubimage(image2.getWidth()/2, image2.getHeight()/2, 100, 200), "500", String.valueOf(c));
                
                hr.Cuthorizontal(image1,image2,image3,rgb);
		vr.CutVertical(image3,image4,1);
		studentid=image4[0];
       		subjectid=image4[1];
		vr.CutVertical(image3,image4,2);
		choid1=image4[0];
		choid2=image4[1];
		choid3=image4[2];
		choid4=image4[3];
		
		int cc=0;
		hr.CutExamHor(choid1,cchoid1);
		for(int i=1;i<31;i++){
			cchoid5[cc]=cchoid1[i];
			cc=cc+1;
		}
		hr.CutExamHor(choid2,cchoid2);
		for(int i=1;i<31;i++){
			cchoid5[cc]=cchoid2[i];
			cc=cc+1;
		}
		hr.CutExamHor(choid3,cchoid3);
		for(int i=1;i<31;i++){
			cchoid5[cc]=cchoid3[i];
			cc=cc+1;
		}
		hr.CutExamHor(choid4,cchoid4);
		for(int i=1;i<31;i++){
			cchoid5[cc]=cchoid4[i];
			cc=cc+1;
		}
				
		hr.CutExamHor(subjectid,csubjectid);
		hr.CutExamHor(studentid,cstudentid);

                
                
		for(int x=0;x<120;x++){
		vr.CutExamVer(cchoid5, cutchoid, x);
		for(int i=0;i<5;i++){
				fullchoid[x][i]=cutchoid[i];
			}
		}
		
		for(int x=1;x<11;x++){
		vr.CutExamVer(csubjectid, csubjectid2, x);
		for(int i=0;i<9;i++){
			chksubjectid[i][x-1]=csubjectid2[i];
		}
		}
		sjid=SC.checksubjectid(chksubjectid);
		buffsubjectid[ce]=sjid;
                
                       
                for(int x=1;x<11;x++){
		vr.CutExamVer(cstudentid, cstudentid2,x);
			for(int i=0;i<14;i++){
				chkstudentid[i][x-1]=cstudentid2[i];
			}
		}
		Stdid=SC.checkstudentid(chkstudentid);
                buffstudentid[ce]=Stdid;
                
                //System.out.println(Stdid);
                
		SC.checkchoid(fullchoid,buffchoid);
                
                
               
                
                BI.tmpwriteImage(studentid, Stdid, "a1");
                BI.tmpwriteImage(subjectid, Stdid, "a2");
                BI.tmpwriteImage(choid1, Stdid, "b1");
                BI.tmpwriteImage(choid2, Stdid, "b2");
                BI.tmpwriteImage(choid3, Stdid, "b3");
                BI.tmpwriteImage(choid4, Stdid, "b4");
                
                for(int i=0;i<120;i++){
                    BI.tmpwriteImage(cchoid5[i], Stdid, String.valueOf(i+1));
                }
                
                
                //System.out.println(chkahngle);
                
                for(int i=0;i<120;i++){
                    for(int j=0;j<5;j++){
                        buffchoidexam[ce][i][j]=buffchoid[i][j];
                    }
                    chartscore[ce][0]=chartscore[ce][0]+buffchoidexam[ce][i][0];
                    chartscore[ce][1]=chartscore[ce][1]+buffchoidexam[ce][i][1];
                    chartscore[ce][2]=chartscore[ce][2]+buffchoidexam[ce][i][2];
                    chartscore[ce][3]=chartscore[ce][3]+buffchoidexam[ce][i][3];
                    chartscore[ce][4]=chartscore[ce][4]+buffchoidexam[ce][i][4];
                }
                
                
                ce=ce+1;    
                
                
           
            }
            proc.setEnabled(true);
            
           
            
}//GEN-LAST:event_jButton6ActionPerformed

private void procActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procActionPerformed
int ck2=0;
 for(int i=0;i<ce;i++){
     jTable3.setValueAt(buffstudentid[i], i, 0);
     for(int x=0;x<50;x++){
         if(id[x].equals(buffstudentid[i])){
             jTable3.setValueAt(name[x]+" "+lastname[x], i, 1);
             ck[ck2]=x;
             ck2=ck2+1;
         }
     }
     jTable3.setValueAt(buffsubjectid[i], i, 2);
 for(int x=0;x<50;x++){
         if(idsubject[x].equals(buffsubjectid[i])){
             jTable3.setValueAt(namesubject[x], i, 3);
         }
     }
 
	for(int k=0;k<120;k++){
		for(int l=0;l<5;l++){
			if(buffchoidexam[i][k][l]+abuffchoid[k][l]==2){
				score[i]=score[i]+1;
			}
		}
	}
        jTable3.setValueAt(score[i], i, 4);
}
 avscore[0]=0;
 avscore[1]=0;
 avscore[2]=0; 
 avscore[3]=0;
 avscore[4]=0;
 avscore[5]=0;
        for(int i=0;i<ce;i++){
        if((score[i]>0)&&(score[i]<21)){
        avscore[0]=avscore[0]+1;
        }
        if((score[i]>20)&&(score[i]<41)){
        avscore[1]=avscore[1]+1;
        }
        if((score[i]>40)&&(score[i]<61)){
        avscore[2]=avscore[2]+1;
        }
        if((score[i]>60)&&(score[i]<81)){
        avscore[3]=avscore[3]+1;
        }
        if((score[i]>80)&&(score[i]<101)){
        avscore[4]=avscore[4]+1;
        }
        if((score[i]>100)&&(score[i]<121)){
        avscore[5]=avscore[5]+1;
        }
        }
        jButton8.setEnabled(true);
        jButton7.setEnabled(true);
        jButton9.setEnabled(true);
}//GEN-LAST:event_procActionPerformed

private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {
            try {
                    File f = new File("D:\\dataexam\\score");
                    boolean mkdir = f.mkdirs();
                   File filex = new File("D:\\dataexam\\score\\score.xls");
                        WorkbookSettings wbSettings = new WorkbookSettings();

                        wbSettings.setLocale(new Locale("en", "EN"));

                        WritableWorkbook workbook = Workbook.createWorkbook(filex, wbSettings);
                        workbook.createSheet("Report", 0);
                        WritableSheet excelSheet = workbook.getSheet(0);
                       Label label = new Label(0,0,"รหัสนักศึกษา");
                       excelSheet.addCell(label);
                       Label label2 = new Label(1,0,"ชื่อ - นามสกุล");
                       excelSheet.addCell(label2);
                       Label label3 = new Label(2,0,"คะแนน");
                       excelSheet.addCell(label3);
                       
                       for(int i=1;i<6;i++){
                       Label label4 = new Label(0,i,"10");
                       excelSheet.addCell(label4);
                       Label label5 = new Label(1,i,"10");
                       excelSheet.addCell(label5);
                       Label label6 = new Label(2,i,"10");
                       excelSheet.addCell(label6);
                       }

                        workbook.write();
                        workbook.close();
               } catch (WriteException ex) {
                   Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
               } catch (IOException ex) {
                   Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
               }

                
            
                   String file="E:\\26122554\\NetBeansProjects\\TEST\\src\\Examreport.jasper";            
                   JasperPrint print = JasperFillManager.fillReport(file, null);
                   JasperViewer jv = new JasperViewer(print,false);
                   jv.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        
}//GEN-LAST:event_jButton7ActionPerformed

private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
// Create a simple Bar chart
    ch1.setText(String.valueOf(avscore[0]+avscore[1]
    +avscore[2]+avscore[3]+avscore[4]+avscore[5]));
    ch2.setText(String.valueOf(avscore[0]));
    ch3.setText(String.valueOf(avscore[1]));
    ch4.setText(String.valueOf(avscore[2]));
    ch5.setText(String.valueOf(avscore[3]));
    ch6.setText(String.valueOf(avscore[4]));
    ch7.setText(String.valueOf(avscore[5]));
DefaultCategoryDataset dataset = new DefaultCategoryDataset();
dataset.setValue(avscore[0], "จำนวนคน", "0-20");
dataset.setValue(avscore[1], "จำนวนคน", "20-40");
dataset.setValue(avscore[2], "จำนวนคน", "40-60");
dataset.setValue(avscore[3], "จำนวนคน", "60-80");
dataset.setValue(avscore[4], "จำนวนคน", "80-100");
dataset.setValue(avscore[5], "จำนวนคน", "100-120");
JFreeChart chart = ChartFactory.createBarChart("ระดับคะแนนนักศึกษา",
"ระดับคะแนน", "คะแนน/คน", dataset, PlotOrientation.VERTICAL,
false, true, false);
try {
File f = new File("D:\\dataexam\\chart");
boolean mkdir = f.mkdirs();
ChartUtilities.saveChartAsJPEG(new File("d:\\dataexam\\chart\\chart.jpg"), chart, 500, 300);
} catch (IOException e) {
System.err.println("Problem occurred creating chart.");
}
chart1.setVisible(true);
chart2.setVisible(false);
checkexam.setVisible(false);
adstudent.setVisible(false);
addsubject.setVisible(false);
ImageIcon icon = new ImageIcon("d:\\dataexam\\chart\\chart.jpg");
jLabel17.setIcon(icon);
}//GEN-LAST:event_jButton8ActionPerformed

private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
chart2.setVisible(true);
chart1.setVisible(false);
checkexam.setVisible(false);
adstudent.setVisible(false);
addsubject.setVisible(false);
for(int i=0;i<ce;i++){
jComboBox1.addItem(buffstudentid[i]);
}
}//GEN-LAST:event_jButton9ActionPerformed

private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
jLabel34.setText(jComboBox1.getSelectedItem().toString());
int csel=jComboBox1.getSelectedIndex();
total.setText(String.valueOf(chartscore[csel][0]+chartscore[csel][1]+chartscore[csel][2]+chartscore[csel][3]+chartscore[csel][4]));
sc1.setText(String.valueOf(chartscore[csel][0]));
sc2.setText(String.valueOf(chartscore[csel][1]));
sc3.setText(String.valueOf(chartscore[csel][2]));
sc4.setText(String.valueOf(chartscore[csel][3]));
sc5.setText(String.valueOf(chartscore[csel][4]));

DefaultCategoryDataset dataset = new DefaultCategoryDataset();
dataset.setValue(chartscore[csel][0], "จำนวนข้อ", "ข้อ ก.");
dataset.setValue(chartscore[csel][1], "จำนวนข้อ", "ข้อ ข.");
dataset.setValue(chartscore[csel][2], "จำนวนข้อ", "ข้อ ค.");
dataset.setValue(chartscore[csel][3], "จำนวนข้อ", "ข้อ ง.");
dataset.setValue(chartscore[csel][4], "จำนวนข้อ", "ข้อ จ.");
JFreeChart chart = ChartFactory.createBarChart("จำนวนข้อของนักศึกษา",
"จำนวนข้อ", "จำนวน/ข้อ", dataset, PlotOrientation.VERTICAL,
false, true, false);
try {
File f = new File("D:\\dataexam\\chartscore");
boolean mkdir = f.mkdirs();
ChartUtilities.saveChartAsJPEG(new File("d:\\dataexam\\chartscore\\"+String.valueOf(csel) +".jpg"), chart, 500, 300);
} catch (IOException e) {
System.err.println("Problem occurred creating chart.");
}
ImageIcon icon = new ImageIcon("d:\\dataexam\\chartscore\\"+String.valueOf(csel) +".jpg");
jLabel32.setIcon(icon);
}//GEN-LAST:event_jComboBox1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addsubject;
    private javax.swing.JPanel adstudent;
    private javax.swing.JLabel answer;
    private javax.swing.JLabel ch1;
    private javax.swing.JLabel ch2;
    private javax.swing.JLabel ch3;
    private javax.swing.JLabel ch4;
    private javax.swing.JLabel ch5;
    private javax.swing.JLabel ch6;
    private javax.swing.JLabel ch7;
    private javax.swing.JPanel chart1;
    private javax.swing.JPanel chart2;
    private javax.swing.JButton checker;
    private javax.swing.JPanel checkexam;
    private javax.swing.JLabel exam;
    private javax.swing.JPanel file;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JButton proc;
    private javax.swing.JPanel process;
    private javax.swing.JLabel sc1;
    private javax.swing.JLabel sc2;
    private javax.swing.JLabel sc3;
    private javax.swing.JLabel sc4;
    private javax.swing.JLabel sc5;
    private javax.swing.JLabel status;
    private javax.swing.JLabel subject;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables


}


